import type { Metadata } from "next";
import { Provider } from "../../../components/Provider";
import { prisma } from '@/lib/prisma'; 
import { notFound } from 'next/navigation';
import OSRequestLinks from "@/app/components/OSRequestLinks";
import ScrollTopLinks from "@/app/hooks/ScrollTopLinks";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function GameLayout({ 
  children, 
  params 
}: { 
  children: React.ReactNode, 
  params: Promise<{ gameId: string }> 
}) {


 const { gameId } = await params;
    
      const idFromUrl = parseInt(gameId.split('-')[0]);

      if (isNaN(idFromUrl)) {
        return notFound();
      }
    
      const game = await prisma.game.findUnique({
        where: {
          id: idFromUrl
        },
        include: { 
          game_media: true, 
          game_genres: { include: { genre: true } } 
        }
      });
    
  
      if (!game) {
        return notFound();
      }

  return (
      <Provider>   
        <div className="mt-5 bg-[#23122E] rounded-2xl p-5" >
        <ScrollTopLinks></ScrollTopLinks>
        <OSRequestLinks  id={game.id} title={game.title}/>
        {children}
        </div>        
      </Provider>

 );
}


