import type { Metadata } from "next";
import { Provider } from "../../../components/Provider";
import { prisma } from '@/lib/prisma'; 
import { notFound } from 'next/navigation';
import OSRequestLinks from "@/app/components/OSRequestLinks";
import ScrollTopLinks from "@/app/hooks/ScrollTopLinks";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function GameLayout({ 
  children, 
  params 
}: { 
  children: React.ReactNode, 
  params: Promise<{ gameId: string }> 
}) {


 const { gameId } = await params;
    
      // 1. Извлекаем ID из начала строки
      // gameId выглядит как "1-hollow-knight-silksong"
      const idFromUrl = parseInt(gameId.split('-')[0]);
    
      // Проверка на случай, если в URL вообще нет числа
      if (isNaN(idFromUrl)) {
        return notFound();
      }
    
      // 2. Ищем игру в базе строго по ID
      // findUnique работает быстрее всего, так как ID — это первичный ключ
      const game = await prisma.game.findUnique({
        where: {
          id: idFromUrl
        },
        include: { 
          game_media: true, 
          game_genres: { include: { genre: true } } 
        }
      });
    
      // 3. Если игра не найдена в базе — показываем 404 
      if (!game) {
        return notFound();
      }
    

    

  return (

          <Provider>
                      
                                
                                <div className="mt-5 bg-[#23122E] rounded-2xl p-5" >
                                   <ScrollTopLinks></ScrollTopLinks>
                                    <OSRequestLinks  id={game.id} title={game.title}/>
                                    {children}
                                </div>
                
        </Provider>

 );
}


